version: '3.3'
services:
  db-mysql-node:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'apiuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Api@user123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'n3tf1n1ty'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql:/var/lib/mysql  
