# @name login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"admin", 
    "password":"123456" 
}

###
POST http://localhost:4000/entradas
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "titulo":"segundo post",
  "contenido" :"este es el contenido",
  "fechaPub" : "2022-09-15",
  "categoria" : {
    "id":1,
    "nombre" : "categoria"
  },
  "tags": [{
    "id":"1",
    "nombre" : "tag1"
  },{
    "nombre": "nueva etiqueta"
  }]
  
}

###
GET http://localhost:4000/entradas/18